name: open_sism
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  flutter_svg: ^0.21.0+1
  rflutter_alert: ^2.0.2
  awesome_dialog: ^1.3.2
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.5
  font_awesome_flutter: ^8.8.1
  flutter_swiper: ^1.1.6
  url_launcher: ^6.0.3
  cached_network_image: ^3.0.0
  google_fonts: ^2.0.0
  intl_phone_number_input: ^0.7.0+1
  flutter_bloc: ^7.0.0
  connectivity_plus: ^1.0.1
  http: ^0.13.3
  double_back_to_close_app: ^2.0.1
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^5.0.0+4
  json_annotation: ^3.0.1
  equatable: ^2.0.0
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  pull_to_refresh: ^2.0.0
  lottie: ^1.0.1
  loading_overlay: ^0.2.1
  shared_preferences: ^2.0.6
  flutter_phoenix: ^1.0.0
  intro_views_flutter: ^3.1.1
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0

  flutter_test:
    sdk: flutter
  #flutter_localizations:
    #sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Chango
      fonts:
        - asset: assets/fonts/Chango-Regular.ttf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Surfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
          weight: 400
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
